version: "3.9"
services:
  api-unica:
    build: .
    ports:
      - "7000:4000"
    volumes:
          - ./src:/app
  mongo-db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
          - ./DB:/data/db
    container_name: new_cs_mongodb
    hostname: new_cs_mongodb